name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: My first step - check out repository
      uses: actions/checkout@v4
    - name: Reimplementing quartio ghp
      uses: ./.github/actions/quarto-ghp
