name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: My first step - check out repository
      uses: actions/checkout@v4
    - name: Reimplementing quarto ci
      uses: ./.github/actions/nbdev-ci
